apiVersion: v1
kind: Service
metadata:
  name: {{.serviceName}}
spec:
  selector:
    app: {{.app}}
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: keystone
  name: {{.deployName}}
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: {{.app}}
      tier: {{.tier}}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{.app}}
        tier: {{.tier}}
    spec:
      containers:
      - image: {{.image}}
        name: keystone-plate
        ports:
        - containerPort: 3000
          protocol: TCP
        volumeMounts:
        - mountPath: /usr/local/src/plate/config.js
          name: keystone-volume
          subPath: config.js
      volumes:
      - name: keystone-volume
        configMap:
          name: keystone-newdb